language: node_js
node_js: 16.15.0

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - npm run build

after_script:
  - cd ./public
  - git init
  - git config user.name "flyingzl"
  - git config user.email "flyingzl@gmail.com"
  - git add .
  - git commit -a -m "fea:更新文章"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  except:
    - master
  only:
    - develop
env:
 global:
   - GH_REF: github.com/flyingzl/flyingzl.github.io.git